export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_ANNOUNCEDINFO_SUCCESS = "LOAD_ANNOUNCEDINFO_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOAD_TWOGBANDSINFO_SUCCESS = "LOAD_TWOGBANDSINFO_SUCCESS";
export const LOAD_SIMINFO_SUCCESS = "LOAD_SIMINFO_SUCCESS";
export const LOAD_WLANINFO_SUCCESS = "LOAD_WLANINFO_SUCCESS";
